---
title: "問卷分析"
author: "統算"
date: "2021/4/28"
output: html_document
---
```{r,echo=FALSE,include=FALSE}
library(tidyverse)
library(qs)
library(ggplot2)
# library(VIM)
# library(mice)
```

```{r}
# data = read.csv("C:/Users/Lai/Desktop/統算期中/responses.csv")
# 
# col = colnames(data)
```

```{r}
# MUSIC = data[,1:19]
# 
# MOVIE = data[,20:31]
# 
# HOBBIES = data[,32:63]
# 
# #恐懼症
# PHOBIAS = data[,64:73] 
# 
# HEALTH_HABITS = data[,74:76]
# 
# PERSONALITY_TRAITS = data[,77:133]
# 
# SPENDING_HABITS = data[,134:140]
# # 人口統計
# DEMOGRAPHICS = data[,141:150]
```

```{r}
# data[,74] %>% table()
# data[which(data[,74]=="current smoker"),74] = 4
# data[which(data[,74]=="former smoker"),74] = 3
# data[which(data[,74]=="tried smoking"),74] = 2
# data[which(data[,74]=="never smoked"),74] = 1
# 
# data[,75] %>% table()
# data[which(data[,75]=="drink a lot"),75] = 3
# data[which(data[,75]=="social drinker"),75] = 2
# data[which(data[,75]=="never"),75] = 1
# 
# 
# data[,108] %>% table()
# data[which(data[,108]=="i am often early"),108] = 3
# data[which(data[,108]=="i am always on time"),108] = 2
# data[which(data[,108]=="i am often running late"),108] = 1
# 
# data[,109] %>% table()
# data[which(data[,109]=="never"),109] = 4
# data[which(data[,109]=="only to avoid hurting someone"),109] = 3
# data[which(data[,109]=="sometimes"),109] = 2
# data[which(data[,109]=="everytime it suits me"),109] = 1
# 
# data[,133] %>% table()
# data[which(data[,133]=="most of the day"),133] = 3
# data[which(data[,133]=="few hours a day"),133] = 2
# data[which(data[,133]=="less than an hour a day"),133] = 1
# data[which(data[,133]=="no time at all"),133] = 1
# 
# data$Gender %>% table()
# data[which(data$Gender=="male"),"Gender"] = 1
# data[which(data$Gender=="female"),"Gender"] = 0
# 
# data$Left...right.handed %>% table()
# data[which(data$Left...right.handed=="right handed"),"Left...right.handed"] = 1
# data[which(data$Left...right.handed=="left handed"),"Left...right.handed"] = 0
# 
# data$Education %>% table()
# data[which(data$Education=="doctorate degree"),"Education"] = 4
# data[which(data$Education=="masters degree"),"Education"] = 4
# data[which(data$Education=="college/bachelor degree"),"Education"] = 3
# data[which(data$Education=="secondary school"),"Education"] = 2
# data[which(data$Education=="primary school"),"Education"] = 1
# data[which(data$Education=="currently a primary school pupil"),"Education"] = 1
# 
# data$Only.child %>% table()
# data[which(data$Only.child=="yes"),"Only.child"] = 1
# data[which(data$Only.child=="no"),"Only.child"] = 0
# 
# data$Village...town %>% table()
# data[which(data$Village...town=="village"),"Village...town"] = 1
# data[which(data$Village...town=="city"),"Village...town"] = 0
# 
# data$House...block.of.flats %>% table()
# data[which(data$House...block.of.flats=="block of flats"),
#      "House...block.of.flats"] = 1
# data[which(data$House...block.of.flats=="house/bungalow"),
#      "House...block.of.flats"] = 0
# 
# for (i in c(1:140,144:150)) {
#   data[,i] = as.numeric(data[,i])
#   data[,i] = as.factor(data[,i])
# }
# for (i in c(141:143)) {
#   data[,i] = as.numeric(data[,i])
# }
```



```{r}
# aggr_plot <- aggr(data, col=c('navyblue','yellow'),
#                   numbers=TRUE, sortVars=TRUE, labels=names(data),
#                   cex.axis=0.7, gap=3, ylab=c("Hist of missing data","Pattern"))
```


```{r}
# mice.data <- mice(data,
#                   m = 1,           # 產生三個被填補好的資料表
#                   maxit = 1,      # max iteration
#                   method = "cart", # 使用CART決策樹，進行遺漏值預測
#                   seed = 188)      # set.seed()，令抽樣每次都一樣
# 
# data_fill = complete(mice.data,action = 1)
# qsave(data_fill,"C:/Users/Lai/Desktop/統算期中/data_fill")
```

```{r}
data = qread("C:/Users/Lai/Desktop/統算期中/28-賴冠維")
```

```{r}
# # 設定Levels
# Factor_Column = which(col %in% c("Smoking","Alcohol",
#                                  "Punctuality","Lying",
#                                  "Internet.usage","Gender",
#                                  "Left...right.handed","Education","Only.child",
#                                  "Village...town","House...block.of.flats"))
# # 數值型變數
# Num_Column = which(col %in% c("Age","Height","Weight"))

```

```{r}
dist.raw <- dist(data)

H = hclust(dist.raw,method = "ward.D2")
# Convert hclust into a dendrogram and plot
plot(H, hang = -1, cex = 0.6,horiz = TRUE)
Group <- cutree(H,k=3)
data$Group = Group
table(Group)
```


```{r}
try = data 
for (i in 1:150) {
  try[,i] = as.numeric(try[,i])
}

```

```{r}
# MUSIC = data[,1:19]
# 
# MOVIE = data[,20:31]
# 
# HOBBIES = data[,32:63]
# 
# #恐懼症
# PHOBIAS = data[,64:73] 
# 
# HEALTH_HABITS = data[,74:76]
# 
# PERSONALITY_TRAITS = data[,77:133]
# 
# SPENDING_HABITS = data[,134:140]
# # 人口統計
# DEMOGRAPHICS = data[,141:150]
```

## 音樂類
```{r}
all = try %>% group_by(Group) %>%
  summarise_at(1:19,mean)

library(pheatmap)
bk <- c(seq(-1,2.9999,by=0.001),
        seq(3.00001,6,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 12,
         main = "Music",
         na_col="white",
         display_numbers = T)
```

## 電影類
```{r}
all = try %>% group_by(Group) %>%
  summarise_at(20:31,mean)

library(pheatmap)
bk <- c(seq(0,2.9999,by=0.001),
        seq(3.00001,6,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         main = "Movies",
         fontsize = 12,
         na_col="white",
         display_numbers = T)
```

## 興趣類
```{r}
all = try %>% group_by(Group) %>%
  summarise_at(32:48,mean)

library(pheatmap)
bk <- c(seq(0,2.9999,by=0.001),
        seq(3.00001,6,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 12,
         main = "Hobbies",
         na_col="white",
         display_numbers = T)
```

```{r}
all = try %>% group_by(Group) %>%
  summarise_at(49:63,mean)

library(pheatmap)
bk <- c(seq(0,2.9999,by=0.001),
        seq(3.00001,6,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 12,
         main = "Hobbies",
         display_numbers = T)
```

```{r}
all = try %>% group_by(Group) %>%
  summarise_at(64:73,mean)

library(pheatmap)
bk <- c(seq(1,2.9999,by=0.001),
        seq(3.00001,5,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 11,
         main = "PERSONALITY_TRAITS",
         display_numbers = T)
```

```{r}
all = try %>% group_by(Group) %>%
  summarise_at(77:92,mean)

library(pheatmap)
bk <- c(seq(1,2.9999,by=0.001),
        seq(3.00001,5,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 11,
         main = "PERSONALITY_TRAITS",
         display_numbers = T)
```

```{r}
all = try %>% group_by(Group) %>%
  summarise_at(93:108,mean)

library(pheatmap)
bk <- c(seq(1,2.9999,by=0.001),
        seq(3.00001,5,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 11,
         main = "PERSONALITY_TRAITS",
         display_numbers = T)
```

```{r}
all = try %>% group_by(Group) %>%
  summarise_at(109:124,mean)

library(pheatmap)
bk <- c(seq(1,2.9999,by=0.001),
        seq(3.00001,5,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 11,
         main = "PERSONALITY_TRAITS",
         display_numbers = T)
```

```{r}
all = try %>% group_by(Group) %>%
  summarise_at(125:133,mean)

library(pheatmap)
bk <- c(seq(1,2.9999,by=0.001),
        seq(3.00001,5,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 11,
         main = "PERSONALITY_TRAITS",
         display_numbers = T)
```

```{r}
all = try %>% group_by(Group) %>%
  summarise_at(134:140,mean)

library(pheatmap)
bk <- c(seq(1,2.9999,by=0.001),
        seq(3.00001,5,by=0.001))
pheatmap(all[,-1],
         color = c(
           colorRampPalette(
             colors = c("navyblue","white"))((length(bk)/2)),
           colorRampPalette(
             colors = c("white","firebrick"))(length(bk)/2)),
         breaks = bk,
         cluster_row = FALSE,
         cluster_cols = FALSE,
         fontsize = 11,
         main = "PERSONALITY_TRAITS",
         display_numbers = T)
```


```{r}
### 重點!!!! summarise_at()用法!!!!!!!!!
Bar_plot = function(data,col_n){
  x = try %>% group_by(Village...town,Group) %>%
    summarise_at(col_n,mean) %>% round(.,digits = 2)
  names(x) = c("Village...town","Group","Mean")
  a = x %>%
    ggplot(aes(x=Group))+
    geom_bar(aes(fill=as.factor(Village...town),weight=Mean),
             colour = "black",
             position = "dodge") +
    scale_fill_brewer(palette = "Set2")+
    labs(x="Group",
         y=NULL,
         fill="Village...town",title = colnames(data)[col_n]) +
    geom_hline(yintercept = 3,linetype= 4,size = 0.5) +
    ylim(0,5)
  return(a)
}
```

```{r}
library(cowplot)

Bar = lapply(1:144, function(a){
  Bar_plot(data = try,col_n = a)
})

i = 19
plot_grid(Bar[[1+4*i]],Bar[[2+4*i]],Bar[[3+4*i]],Bar[[4+4*i]])

```

```{r}
x = try %>% group_by(Gender,Group) %>%
  summarise(N = table(Group))

x %>%
  group_by(Gender,Group) %>%
  summarise(N) %>%
  ggplot(mapping = aes(
    x = as.factor(Group), fill = as.factor(Gender), y = N))+
  geom_col(position =position_dodge(0.9),width = 0.8,colour = "black")+
  geom_text(aes(label=N),
            position = position_dodge(width = 0.9),
            vjust=-0.5,
            color="black", size=4)+
  theme(axis.text.x = element_text(vjust=0.5,size=11),
        legend.text=element_text(size=9),legend.title=element_text(size=11))+
  scale_fill_brewer(palette = "Set2")+
    labs(x="Group",
         y=NULL,
         fill="Gender",title = "Gender / Group")+
  scale_colour_hue(labels=c("Female","Male"))
```

```{r}

x = try %>% group_by(Gender,Alcohol) %>%
  summarise(N = table(Alcohol))

x %>%
  group_by(Gender,Alcohol) %>%
  summarise(N) %>%
  ggplot(mapping = aes(
    x = as.factor(Gender), fill = as.factor(Alcohol), y = N))+
  geom_col(position =position_dodge(0.9),width = 0.8,colour = "black")+
  geom_text(aes(label=N),
            position = position_dodge(width = 0.9),
            vjust=-0.5,
            color="black", size=4)+
  theme(axis.text.x = element_text(vjust=0.5,size=11),
        legend.text=element_text(size=9),legend.title=element_text(size=11))+
  scale_fill_brewer(palette = "Set2")+
    labs(x="Gender",
         y=NULL,
         fill="Alcohol",title = "Gender / Alcohol")

```




```{r}
data$Alcohol_addicted = ifelse(data$Alcohol==3,1,0)
data$Alcohol = NULL

```

# 看0,1比例拆Train/Test (70,30)

```{r}
library(cluster)
data_Positive <- data[data$Alcohol_addicted==1,];dim(data_Positive)

k.max <- 10
asw <- rep(NA,10)
for(i in 2:k.max){
  asw[i] = clara(data_Positive,i)$silinfo$avg.width
}

k.best <- which.min(asw)
plot(2:10, asw[2:10],
     type="l", pch = 19, frame = FALSE,
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

clustering <- clara(data_Positive,k.best)
data_Positive_cluster <- data.frame(data_Positive,clustering$cluster)

cluster_p = lapply(1:max(data_Positive_cluster$clustering.cluster), function(a){
  data_Positive_cluster[data_Positive_cluster$clustering.cluster==a,][,1:ncol(data)]
})

cluster_p_1 = lapply(1:max(data_Positive_cluster$clustering.cluster), function(a){
  set.seed(12345)
  x = cluster_p[[a]]
  x[sample(nrow(x),0.7*nrow(x),replace=F),]
})

only_1 = cluster_p_1[[1]]
for (i in 2:length(cluster_p_1)) {
  only_1 = rbind(only_1,cluster_p_1[[i]])
}
```


## Bankrupty為0
```{r}
set.seed(12345)
data_Negative <- data[data$Alcohol_addicted==0,];dim(data_Negative)
k.max <- 10
asw <- rep(NA,10)
for(i in 2:k.max){
  asw[i] = clara(data_Negative,i)$silinfo$avg.width
}
k.best <- which.min(asw)
plot(2:10, asw[2:10],
     type="l", pch = 19, frame = FALSE,
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

clustering <- clara(data_Negative,k.best)
data_Negative_cluster <- data.frame(data_Negative,clustering$cluster)

cluster_p = lapply(1:max(data_Negative_cluster$clustering.cluster), function(a){
  data_Negative_cluster[data_Negative_cluster$clustering.cluster==a,][,1:ncol(data)]
})

cluster_p_1 = lapply(1:max(data_Negative_cluster$clustering.cluster), function(a){
  set.seed(12345)
  x = cluster_p[[a]]
  x[sample(nrow(x),0.7*nrow(x),replace=F),]
})

only_0 = cluster_p_1[[1]]
for (i in 2:length(cluster_p_1)) {
  only_0 = rbind(only_0,cluster_p_1[[i]])
}
```



```{r}
train = rbind(only_0,only_1)
train$Alcohol_addicted %>% table()

test = data[-as.numeric(rownames(train)),]
```


```{r}
table(train$Alcohol_addicted)
data_Positive <- train[train$Alcohol_addicted==1,];dim(data_Positive)
k.max <- 10
asw <- rep(NA,10)
for(i in 2:k.max){
  asw[i] = clara(data_Positive,i)$silinfo$avg.width
}

k.best <- which.min(asw)
plot(2:10, asw[2:10],
     type="l", pch = 19, frame = FALSE,
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

clustering <- clara(data_Positive,k.best)
data_Positive_cluster <- data.frame(data_Positive,clustering$cluster)

cluster_p = lapply(1:max(data_Positive_cluster$clustering.cluster), function(a){
  data_Positive_cluster[data_Positive_cluster$clustering.cluster==a,][,1:ncol(data)]
})

cluster_p_1 = lapply(1:max(data_Positive_cluster$clustering.cluster), function(a){
  set.seed(12345)
  x = cluster_p[[a]]
  x[sample(nrow(x),4*nrow(x),replace=T),]
})

only_1 = cluster_p_1[[1]]
for (i in 2:length(cluster_p_1)) {
  only_1 = rbind(only_1,cluster_p_1[[i]])
}
```


```{r}
set.seed(12345)
data_Negative <- train[train$Alcohol_addicted==0,];dim(data_Negative)
k.max <- 10
asw <- rep(NA,10)
for(i in 2:k.max){
  asw[i] = clara(data_Negative,i)$silinfo$avg.width
}
k.best <- which.min(asw)
plot(2:10, asw[2:10],
     type="l", pch = 19, frame = FALSE,
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

clustering <- clara(data_Negative,k.best)
data_Negative_cluster <- data.frame(data_Negative,clustering$cluster)

cluster_p = lapply(1:max(data_Negative_cluster$clustering.cluster), function(a){
  data_Negative_cluster[data_Negative_cluster$clustering.cluster==a,][,1:ncol(data)]
})

cluster_p_1 = lapply(1:max(data_Negative_cluster$clustering.cluster), function(a){
  set.seed(12345)
  x = cluster_p[[a]]
  x[sample(nrow(x),1*nrow(x),replace=F),]
})

only_0 = cluster_p_1[[1]]
for (i in 2:length(cluster_p_1)) {
  only_0 = rbind(only_0,cluster_p_1[[i]])
}

train_balance = rbind(only_0,only_1)
train_balance$Alcohol_addicted %>% table()
```


```{r}
library(xgboost)
xgb.params = list(
  objective = "binary:logistic", 
  subsample = 0.4,
  booster="gbtree",
  colsample_bytree = 0.4,
  set.seed = 77777,
  max_depth = 3,
  eta = 0.02, 
  eval_metric = "error",
  gamma = 0
)

cv.model <- xgb.cv(
  data = data.matrix(subset(train_balance, select = -Alcohol_addicted)),
  label = train_balance$Alcohol_addicted,
  params = xgb.params,
  nrounds = 400,
  nfold = 6,
  print_every_n = 10,
  early_stopping_rounds = 30
)
```


```{r}
tmp = cv.model$evaluation_log

plot(x=1:nrow(tmp), y= tmp$train_error_mean,
     col='red', xlab="nround", ylab="AUC",type="l", main="Avg.Performance in CV")
lines(x=1:nrow(tmp), y= tmp$test_error_mean, col='blue')

legend("topright", pch=1, col = c("red", "blue"),
       legend = c("Train", "Validation") )
```


# 建模
```{r,include = FALSE}
best.nrounds = cv.model$best_iteration

xgb.model <- xgboost::xgboost(
  data.matrix(subset(train_balance,
                     select = -Alcohol_addicted)),
  label = train_balance$Alcohol_addicted,
  params = xgb.params,
  nrounds = best.nrounds)
```

# 在Test表現
```{r}
dtest = data.matrix(subset(test, select = -Alcohol_addicted))
xgb.pred = predict(xgb.model,dtest,reshape=T,type="response")
fit = ifelse(xgb.pred>0.5,1,0)

library(caret)
xtab <- table(fit,test$Alcohol_addicted)
print(confusionMatrix(xtab[2:1,2:1]))
```

# ROC/Recall
```{r}
library(precrec)
precrec_obj <- evalmod(scores = xgb.pred, labels = test$Alcohol_addicted)
precrec_obj
autoplot(precrec_obj)
```


# Importance Plot
```{r}
library(vip)
vip(xgb.model, num_features = 20)
```


# 取前20有解釋力變數
```{r}
select = vip(xgb.model, num_features = 20)
col = select$data[1]

select_col = c(col$Variable,"Alcohol_addicted")
# CART
train_balance_select = train_balance[,select_col]
test_select = test[,select_col]
data_select = data[,select_col]

```


```{r}

raw = sapply(1:(ncol(data_select)-1), function(a){
  data_select[,a] %>% as.numeric()
})


library(psych)
correlations <- cor(raw)
fa.parallel(correlations,n.obs = 500)


EFA_model <- fa(raw,nfactors = 3,rotate = "varimax",fm = "old.min")
EFA_model
factor.plot(EFA_model,
            labels = rownames(EFA_model$loadings),pos = 2)

print(EFA_model)
plot(EFA_model)
fa.diagram(EFA_model, digits = 2)

```



```{r}
library(qgraph)
names = c(1:20) %>% as.character()
corMat <- cor_auto(raw) # Correlate data

loading = lapply(1:3, function(a){
  which(abs(EFA_model[["Structure"]][,a])>0.35) %>% as.numeric()
})

Graph_lasso <- qgraph(corMat, graph = "glasso",
                      layout = "spring", tuning = 0.4,
                      sampleSize = nrow(raw),
                      legend.cex = 0.4, vsize = 7,esize = 12,
                      posCol = "#003399", negCol = "#FF9933",
                      vTrans = 300,groups=loading,
                      color=c("red", "orange", "yellow", "lightblue", "green"),
                      nodeNames = select_col[-21], labels = names)
```




```{r}
num_index = which(colnames(data_select) %in% c("Weight","Age","Height"))
col_index = which(!(colnames(data_select) %in% c("Weight","Age","Height")))

for (i in num_index) {
  data_select[,i] = as.numeric(data_select[,i])
}
for (i in col_index) {
    data_select[,i] = as.factor(data_select[,i])
}
```

```{r}
Perc = function(x, colInd, data.level){
  perc_default = list()
  for (i in 1:length(data.level)) {
    data_choose = x[which(x[,colInd]==data.level[i]),"Alcohol_addicted"] %>%
      as.data.frame()
    default_count = table(data_choose)[2] %>% as.numeric()
    total_count = nrow(data_choose)
    perc = round(default_count/total_count,4)
    perc_default[[i]] = data.frame(
      level = data.level[i],
      total_count=total_count,
      default_count=default_count,
      perc=perc)
  }
  x = perc_default[[1]]
  for (i in 2:length(data.level)) {
    x = rbind(x,perc_default[[i]])
  }
  return(x)
}
```

```{r}
n = 3

x = Perc(x = data_select,
         colInd = n,
         data.level = levels(data_select[,n]))

xlab = colnames(data_select)[n]
title = paste0(xlab," Levels v.s. Alcohol Addicted")

ggplot(data = x, mapping = aes(x = reorder(level, perc), y = perc,fill=level)) +
  geom_bar(stat = "identity",colour="black") +
  coord_flip() +
  xlab(xlab) +
  ylab("Percentage of Alcohol Addicted") +
  ggtitle(title) +
  geom_label(label = paste(100*x$perc, "%"))+
  scale_fill_brewer(palette="Pastel2")

```



```{r}
select = vip(xgb.model, num_features = 40)
d = select$data
all = sum(d$Importance)
d$Weight = d$Importance/all

select_col = c(d$Variable,"Alcohol_addicted")
```


```{r}
data_select = data[,select_col]

select_num = select_col[c(10,16,23)] # 10,16,23
select_cat = select_col[c(1:9,11:15,17:22,24:40)]

index = which(colnames(data_select) %in% select_cat)

```


```{r}
t = sapply(index, function(a){
  n = a
  x = Perc(x = data_select,
           colInd = n,
           data.level = levels((data_select[,n])))
  x[which.max(x$perc),"level"]
  P.N = ifelse(x[which.max(x$perc),"level"] %in% c(3,4,5),"P","N")
  cbind(colnames(data_select)[n],P.N)
})

t = t(t) %>% as.data.frame()

t[which(t$V1 %in% colnames(data)[1:19]),"Cat"] = "Music"
t[which(t$V1 %in% colnames(data)[20:31]),"Cat"] = "Movie"
t[which(t$V1 %in% colnames(data)[32:63]),"Cat"] = "Hobbies"
t[which(t$V1 %in% colnames(data)[64:73]),"Cat"] = "Phobias"
t[which(t$V1 %in% colnames(data)[74:76]),"Cat"] = "Health"
t[which(t$V1 %in% colnames(data)[77:133]),"Cat"] = "Personality"
t[which(t$V1 %in% colnames(data)[134:140]),"Cat"] = "Spending"

# MUSIC = data[,1:19]
# MOVIE = data[,20:31]
# HOBBIES = data[,32:63]
# #恐懼症
# PHOBIAS = data[,64:73] 
# HEALTH_HABITS = data[,74:76]
# PERSONALITY_TRAITS = data[,77:133]
# SPENDING_HABITS = data[,134:140]

t$Weight = d[which(d$Variable %in% t$V1),"Weight"]
names(t) = c("Variable","P.N","Category","W")

# N = sapply(1:3, function(a){
#   c(select_num[a],"P","Num",d$Weight[which(d$Variable %in% select_num[a])])
# })
# N = t(N) %>% as.data.frame()
# names(N) = c("Variable","P.N","Category","W")
# N$W = as.numeric(N$W)
# t = rbind(t,N)
```

# 計算加權後
## P
```{r}
t_P = t %>% filter(P.N=="P") %>%
  summarise(Variable,Category,W)

tt = try[,which(colnames(try)%in% t_P$Variable)]  

tt_weight = sapply(1:ncol(tt),function(a){
  tt[,a]*t_P[which(t_P$Variable %in% colnames(tt)[a]),"Weight"]
})

tt_weight = as.data.frame(tt_weight)
colnames(tt_weight) = t_P$Variable
```

```{r}
tt_weight_positive = rowSums(tt_weight)
```

```{r}
Music_ind = which(colnames(tt_weight) %in% colnames(data)[1:19])
Music = rowSums(tt_weight[,Music_ind])

Hobbies_ind = which(colnames(tt_weight) %in% colnames(data)[32:63])
Hobbies = rowSums(tt_weight[,Hobbies_ind])

Health_ind = which(colnames(tt_weight) %in% colnames(data)[74:76])
Health = (tt_weight[,Health_ind])

PERSONALITY_ind = which(colnames(tt_weight) %in% colnames(data)[77:133])
Personality = rowSums(tt_weight[,PERSONALITY_ind])

SPENDING_ind = which(colnames(tt_weight) %in% colnames(data)[134:140])
SPENDING = rowSums(tt_weight[,SPENDING_ind])

P = cbind(Music,Hobbies,Health,Personality,SPENDING) %>% as.data.frame()

```



## N
```{r}
t_N = t %>% filter(P.N=="N") %>%
  summarise(Variable,Category,W)

tt = try[,which(colnames(try)%in% t_N$Variable)]  

tt_weight = sapply(1:ncol(tt),function(a){
  (6-tt[,a])*t_N[which(t_N$Variable %in% colnames(tt)[a]),"Weight"]
})

tt_weight = as.data.frame(tt_weight)
colnames(tt_weight) = t_N$Variable
```

```{r}
tt_weight_negative = rowSums(tt_weight)
```


```{r}
Music_ind = which(colnames(tt_weight) %in% colnames(data)[1:19])
Music = (tt_weight[,Music_ind])

Hobbies_ind = which(colnames(tt_weight) %in% colnames(data)[32:63])
Hobbies = (tt_weight[,Hobbies_ind])

Health_ind = which(colnames(tt_weight) %in% colnames(data)[74:76])
Health = rowSums(tt_weight[,Health_ind])

PERSONALITY_ind = which(colnames(tt_weight) %in% colnames(data)[77:133])
Personality = rowSums(tt_weight[,PERSONALITY_ind])

SPENDING_ind = which(colnames(tt_weight) %in% colnames(data)[134:140])
SPENDING = rowSums(tt_weight[,SPENDING_ind])

N = cbind(Music,Hobbies,Health,Personality,SPENDING) %>% as.data.frame()

```

```{r}
A = P+N
A$Y = data$Alcohol_addicted
```


```{r}
GMM = cbind(tt_weight_positive,tt_weight_negative,data_select$Alcohol_addicted) %>%
  as.data.frame()
names(GMM) = c("Positive","Negative","Y")

```

```{r}
P = GMM$Positive %>% as.data.frame()
N = GMM$Negative %>% as.data.frame()
P$Category = "Positive"
N$Category = "Negative"

a <- rbind(P, N)
ggplot(a, aes(., fill = Category)) + geom_density(alpha = 0.2)

```

```{r}
GMM$Sum = rowSums(GMM[,1:2])
require(mclust)

class = GMM$Y
mod2 = MclustDA(GMM[,c(1,2,4)],class = class,modelType = "MclustDA")
summary(mod2, parameters = TRUE)

```


```{r}
plot(mod2, what = "classification")
```


```{r}
plot(mod2, what = "scatterplot")
```

```{r}
GMM_prob = predict(mod2)
p = GMM_prob$z[,2]

precrec_obj <- evalmod(scores = p, labels = GMM$Y)
precrec_obj
autoplot(precrec_obj)

```






